name: Deploy to S3

on:
  push:
    branches:
      - main  # or the branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # or your desired region

    - name: Sync files to S3
      run: |
        BUCKET_NAME="borisosipchuk.com"
        DIRECTORY_STYLES="styles"
        DIRECTORY_FILES="files"
        FILE_NAME_INDEX="index.html"
        FILE_NAME_STYLE="borisosipchuk.css"
        FILE_NAME_RESUME_DOCX="2024-09_Boris_Osipchuk_Resume.docx"
        FILE_NAME_RESUME_PDF="2024-09_Boris_Osipchuk_Resume.pdf"

        aws s3 cp "$FILE_NAME_INDEX" "s3://$BUCKET_NAME/" --acl public-read
        
        # Check if the styles directory exists
        if aws s3 ls "s3://$BUCKET_NAME/$DIRECTORY_STYLES/" 2>&1 | grep -q 'PRE'; then
          echo "Directory exists, uploading the file..."
        else
          echo "Directory does not exist, creating the directory..."
          
          # Create the directory by uploading an empty object with a trailing slash
          # aws s3 cp "$DIRECTORY_STYLES/$FILE_NAME_STYLE" "s3://$BUCKET_NAME/$DIRECTORY_STYLES/" --acl public-read
          
          # Use aws s3api to explicitly create the directory (prefix)
          aws s3api put-object --bucket "$DIRECTORY_STYLES/$FILE_NAME_STYLE" --key "$DIRECTORY"
        fi       

        # Upload the file to the directory
        #aws s3 cp "$DIRECTORY_STYLES/$FILE_NAME_STYLE" "s3://$BUCKET_NAME/$DIRECTORY_STYLES/" --acl public-read
        


        
