name: Deploy to S3

on:
  push:
    branches:
      - main  # or the branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # or your desired region

    - name: Sync files to S3
      run: |
        aws s3 cp index.html s3://borisosipchuk.com/index.html --acl public-read
